apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
#  finalizers:
#    - delete-s3-backup
  name: backup1
spec:
  pxcCluster: cluster1
  storageName: fs-pvc
#  containerOptions:
#    env:
#    - name: VERIFY_TLS
#      value: "false"
#    extraArgs:
#      xtrabackup:
#      - "--someflag=abc"
#      xbcloud:
#      - "--someflag=abc"
#      xbstream:
#      - "--someflag=abc"
