apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: restore1
#  annotations:
#    percona.com/headless-service: "true"
spec:
  pxcCluster: cluster1
  backupName: backup1
#  backupSource:
#    destination: s3://S3-BUCKET-NAME/BACKUP-NAME
#    s3:
#      bucket: S3-BINLOG-BACKUP-BUCKET-NAME-HERE
#      credentialsSecret: my-cluster-name-backup-s3
#      endpointUrl: https://s3.us-west-2.amazonaws.com/
#      region: us-west-2
#  pitr:
#    type: latest
#    date: "yyyy-mm-dd hh:mm:ss"
#    gtid: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee:nnn"
#    backupSource:
#      storageName: "STORAGE-NAME-HERE"
#      s3:
#        bucket: S3-BINLOG-BACKUP-BUCKET-NAME-HERE
#        credentialsSecret: my-cluster-name-backup-s3
#        endpointUrl: https://s3.us-west-2.amazonaws.com/
#        region: us-west-2
