apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: restore1
#  annotations:
#    percona.com/headless-service: "true"
spec:
  pxcCluster: cluster1
  backupName: backup1
#  containerOptions:
#    env:
#    - name: VERIFY_TLS
#      value: "false"
#    args:
#      xtrabackup:
#      - "--someflag=abc"
#      xbcloud:
#      - "--someflag=abc"
#      xbstream:
#      - "--someflag=abc"
#  resources:
#    requests:
#      memory: 100M
#      cpu: 100m
#    limits:
#      memory: 200M
#      cpu: 200m
#  backupSource:
#    verifyTLS: true
#    destination: s3://S3-BUCKET-NAME/BACKUP-NAME or destination: azure://CONTAINER-NAME/BACKUP-NAME
#    s3:
#      bucket: S3-BINLOG-BACKUP-BUCKET-NAME-HERE
#      credentialsSecret: my-cluster-name-backup-s3
#      endpointUrl: https://s3.us-west-2.amazonaws.com/
#      region: us-west-2
#    azure:
#      container: <your-container-name>
#      credentialsSecret: my-cluster-name-backup-azure
#  pitr:
#    type: latest
#    date: "yyyy-mm-dd hh:mm:ss"
#    gtid: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee:nnn"
#    backupSource:
#      verifyTLS: true
#      storageName: "STORAGE-NAME-HERE"
#      s3:
#        bucket: S3-BINLOG-BACKUP-BUCKET-NAME-HERE
#        credentialsSecret: my-cluster-name-backup-s3
#        endpointUrl: https://s3.us-west-2.amazonaws.com/
#        region: us-west-2
