apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manager-namespace.yaml
commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/instance: percona-xtradb-cluster-operator
  app.kubernetes.io/name: percona-xtradb-cluster-operator
  app.kubernetes.io/part-of: percona-xtradb-cluster-operator
images:
  - name: pxc-operator
    newName: perconalab/percona-xtradb-cluster-operator
    newTag: 1.15.0
