apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: perconaxtradbclusters.pxc.percona.com
spec:
  group: pxc.percona.com
  names:
    kind: PerconaXtraDBCluster
    listKind: PerconaXtraDBClusterList
    plural: perconaxtradbclusters
    singular: perconaxtradbcluster
    shortNames:
    - pxc
    - pxcs
  scope: Namespaced
  versions:
    - name: v1
      storage: true
      served: true
    - name: v1alpha1
      storage: false
      served: true
  additionalPrinterColumns:
    - name: Endpoint
      type: string
      JSONPath: .status.host
    - name: Status
      type: string
      JSONPath: .status.state
    - name: PXC
      type: string
      description: Ready pxc nodes
      JSONPath: .status.pxc.ready
    - name: proxysql
      type: string
      description: Ready pxc nodes
      JSONPath: .status.proxysql.ready
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: perconaxtradbclusterbackups.pxc.percona.com
spec:
  group: pxc.percona.com
  names:
    kind: PerconaXtraDBClusterBackup
    listKind: PerconaXtraDBClusterBackupList
    plural: perconaxtradbclusterbackups
    singular: perconaxtradbclusterbackup
    shortNames:
    - pxc-backup
    - pxc-backups
  scope: Namespaced
  versions:
    - name: v1
      storage: true
      served: true
  additionalPrinterColumns:
    - name: Cluster
      type: string
      description: Cluster name
      JSONPath: .spec.pxcCluster
    - name: Storage
      type: string
      description: Storage name from pxc spec
      JSONPath: .status.storageName
    - name: Destination
      type: string
      description: Backup destination
      JSONPath: .status.destination
    - name: Status
      type: string
      description: Job status
      JSONPath: .status.state
    - name: Completed
      description: Completed time
      type: date
      JSONPath: .status.completed
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: perconaxtradbclusterrestores.pxc.percona.com
spec:
  group: pxc.percona.com
  names:
    kind: PerconaXtraDBClusterRestore
    listKind: PerconaXtraDBClusterRestoreList
    plural: perconaxtradbclusterrestores
    singular: perconaxtradbclusterrestore
    shortNames:
    - pxc-restore
    - pxc-restores
  scope: Namespaced
  versions:
    - name: v1
      storage: true
      served: true
  additionalPrinterColumns:
    - name: Cluster
      type: string
      description: Cluster name
      JSONPath: .spec.pxcCluster
    - name: Status
      type: string
      description: Job status
      JSONPath: .status.state
    - name: Completed
      description: Completed time
      type: date
      JSONPath: .status.completed
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: perconaxtradbbackups.pxc.percona.com
spec:
  group: pxc.percona.com
  names:
    kind: PerconaXtraDBBackup
    listKind: PerconaXtraDBBackupList
    plural: perconaxtradbbackups
    singular: perconaxtradbbackup
    shortNames: []
  scope: Namespaced
  versions:
    - name: v1alpha1
      storage: true
      served: true
  additionalPrinterColumns:
    - name: Cluster
      type: string
      description: Cluster name
      JSONPath: .spec.pxcCluster
    - name: Storage
      type: string
      description: Storage name from pxc spec
      JSONPath: .status.storageName
    - name: Destination
      type: string
      description: Backup destination
      JSONPath: .status.destination
    - name: Status
      type: string
      description: Job status
      JSONPath: .status.state
    - name: Completed
      description: Completed time
      type: date
      JSONPath: .status.completed
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: percona-xtradb-cluster-operator
rules:
- apiGroups:
  - pxc.percona.com
  resources:
  - perconaxtradbclusters
  - perconaxtradbclusters/status
  - perconaxtradbclusterbackups
  - perconaxtradbclusterbackups/status
  - perconaxtradbclusterrestores
  - perconaxtradbclusterrestores/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - configmaps
  - services
  - persistentvolumeclaims
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - certmanager.k8s.io
  resources:
  - issuers
  - certificates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: percona-xtradb-cluster-operator
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: service-account-percona-xtradb-cluster-operator
subjects:
- kind: ServiceAccount
  name: percona-xtradb-cluster-operator
roleRef:
  kind: Role
  name: percona-xtradb-cluster-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: percona-xtradb-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: percona-xtradb-cluster-operator
  template:
    metadata:
      labels:
        name: percona-xtradb-cluster-operator
    spec:
      serviceAccountName: percona-xtradb-cluster-operator
      containers:
        - name: percona-xtradb-cluster-operator
          image: percona/percona-xtradb-cluster-operator:1.1.0
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - percona-xtradb-cluster-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "percona-xtradb-cluster-operator"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secrets
type: Opaque
data:
  root: cm9vdF9wYXNzd29yZA==
  xtrabackup: YmFja3VwX3Bhc3N3b3Jk
  monitor: bW9uaXRvcg==
  clustercheck: Y2x1c3RlcmNoZWNrcGFzc3dvcmQ=
  proxyadmin: YWRtaW5fcGFzc3dvcmQ=
  pmmserver: c3VwYXxefHBheno=
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-ssl
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQWR5Z0F3SUJBZ0lVTjYzV1BvVjZoNG1wTUF1VlgrS0RnUFZKZkpRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF4TUhVbTl2ZENCRFFUQWVGdzB4T1RBMU1EY3hNakF5TURCYUZ3MHlOREExTURVeApNakF5TURCYU1CSXhFREFPQmdOVkJBTVRCMUp2YjNRZ1EwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRRG1UUXI2L0VoTkJRZyszWUdSdVpRN3g1NXdzODN2Yy9qem9vTVJtbCtyWEVkUm55RVIKR2xWRy9CcmU1clQ4d203cklWcWdhLzJYR0tXQ1NYdnZOYWJ2bjV0QTNZVmllcnZ6aXdPM0E1SU5jQ0gxelM0NApMc3ZFS0VaZno0b3dia1lyVy9FMzdHWmVTQTF4THB3aWFJVFh5b0YvRVM4WGRaNWtmZlk3QzV1NkErWXE4UXArCjZOdFltaTBzdURlSmVzWVNCbnRoVkdhakt2b2ZxeFNCUTk1Q1VVMXBCN0RKejB1dGd3VU9acUk5VTdYS3hUWjUKN2hVZlM3TGZ5amdoS1Z3QzBRUVVzaEVPZ09TdTU4UTNnQWpFTXJ2azBpc2RBbWdGR2hBNk1wTU5yY0JWcHFhRgpkWXN3MnI5YXBRdnQwc3E2MitXT2xEM21kWFRZRkJ6SXpqTFRBZ01CQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFCkF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlRaUmRpU2NGcGVJdEVIcFAyODl2NEQKNHl0OG5UQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF6NkRPY2d2VkVpLzhvQXRvRGdGeGNqTE9sVzBmSEI1MApaVHlwZzhBZGRDK2tsc2NGSGNwelpLMC83alJPa29ieHBZbldOMlZqMVRzOWh5em5IN05QUVl2R3dBOGowOU9DCjhKaTlYNVF0VmdQVG5SUXRmUWFkTTJzcjA0ZDBMUGVrWFE3Y2JwOWFhdCsyQVVCSEdUcHVIZjFnL2Q4SUladkEKYU1pZkU0YjVkNHgrUkpzeHNoenJvWUo1VDY2YXE3b3lLVFY2S2hMVnJyTmlYaHZSc29PNWRDRFJxaU1UdjZPdApsZGFRUDZCOTY2QWluTTQvQ0ZFU0llTkFwZk5CWU1BZ0wzb2FLTklSQVdmemxhb0RFM2ZmZ1htTzNyZlc4dlN0ClZPQUtSd0xZdDkzVWN6TUptMVRJN3NscytJUEVRY0FvSHdYM3JmbFQwK2FibzNnblNydUw0QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnekNDQW11Z0F3SUJBZ0lVZVV3RVh4SzM3MEJnY0tOMys5Y1ZYOTIvVmNVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF4TUhVbTl2ZENCRFFUQWVGdzB4T1RBMU1EY3hNakF5TURCYUZ3MHlNREExTURZeApNakF5TURCYU1CY3hGVEFUQmdOVkJBTVRER05zZFhOMFpYSXhMWEI0WXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUwxY2VDQXNGb3ZLR0JQbWpxZUROdDlCSFVlTVZHTTYvWTlUTEV5bEZsVnMKckV0RzY5UXppS2JEU2M3WjJXUlFCRDdJaHVXN2h6SlpxTlc1YmxvSlIrTzVCY09XWTZGTll4dVJ1U0t1S2NlcAo0VEhnNXI1T1VJOHZvVmsvZWZTYUdVbG9wMStHVHJFS3ltWWtZUis1dFBuTEYwYWVDSU92VVk5ZVlHZjEyVE16Cjdlcm1zMGd6d01JRGY2aml6a0lPRURONVY4Y09TR1dBRW1haFVlYllFdldzWjN2OGdvclcvSVBLQWtWOHFnaU8KZ3l0RllobkdneGF0b3ZCSmFYeDVMbDJoOHVhNnVNYUMxVjM2WWpYa3lDZmprcWh4M2hWdkhHTVppaEpKMzVVUgoremEwd0RlSU8yQUxXTTdjVkhaN2lxNklHaldYNjdCMjZxazFiaU1aUkJVQ0F3RUFBYU9CeXpDQnlEQU9CZ05WCkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWQKRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkMrdUJFK0E1YnpVeXp1Tk9RZDJOc3MvckttaU1COEdBMVVkSXdRWQpNQmFBRk5sRjJKSndXbDRpMFFlay9iejIvZ1BqSzN5ZE1Fa0dBMVVkRVFSQ01FQ0NFV05zZFhOMFpYSXhMWEJ5CmIzaDVjM0ZzZ2hzcUxtTnNkWE4wWlhJeExYQnliM2g1YzNGc0xYVnVjbVZoWkhtQ0Rpb3VZMngxYzNSbGNqRXQKY0hoak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkZqcjdkenhsbDZFR0lyb3NtMEJZdWZwR3JnWUh3UXJSeQpGWDJyY0xsNVhYblZwMmt2MUZyMkxubDlhblJZN005eHo0czM4TDJhZ2Z3Y2tVdWVFZERERlVsWmgxbmNDY2JyCjVPa0J1cER3TlJUbnVzOFJFY3VuV3FhNS82VnU0Y1BzeFIzcUk4d3cybFN3L0l1YUxVNXZKUmQzVjdLWjlPbW8KendGQVRQS3dIUHl5RG1nV2NKdEFNcmdMakRIeURncmd1KzJMZG5wb1Qrd2ExNGxud2RjM2VWQ2pJWk1HTEtscQpuenU3UjJUSzF5bXJVTEJDZHB6eWwzT1ZPdmhVeWttdkhkUUhDS2FvNk9QbkJKMllGWHBHTkdIRGd1dUU1T09OCk9qMW9WRFFlMHJCOWloKzcxQzYxNHFJV3R1cnJjNTZTZnc2QkRrR2E4emQ0aENvNlllb2kKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdlZ4NElDd1dpOG9ZRSthT3A0TTIzMEVkUjR4VVl6cjlqMU1zVEtVV1ZXeXNTMGJyCjFET0lwc05KenRuWlpGQUVQc2lHNWJ1SE1sbW8xYmx1V2dsSDQ3a0Z3NVpqb1Uxakc1RzVJcTRweDZuaE1lRG0Kdms1UWp5K2hXVDk1OUpvWlNXaW5YNFpPc1FyS1ppUmhIN20wK2NzWFJwNElnNjlSajE1Z1ovWFpNelB0NnVhegpTRFBBd2dOL3FPTE9RZzRRTTNsWHh3NUlaWUFTWnFGUjV0Z1M5YXhuZS95Q2l0YjhnOG9DUlh5cUNJNkRLMFZpCkdjYURGcTJpOEVscGZIa3VYYUh5NXJxNHhvTFZYZnBpTmVUSUorT1NxSEhlRlc4Y1l4bUtFa25mbFJIN05yVEEKTjRnN1lBdFl6dHhVZG51S3JvZ2FOWmZyc0hicXFUVnVJeGxFRlFJREFRQUJBb0lCQUMzNXpaRENJNWM5TWl0aQp4ekFVdzdYZzhXTDF4MmR3WXkveFdjZ2lMUklBbUxTT082UUIveU8rTnFWcWIwWFR4N1FXcStvTFpmL3JsUHFQClV5TzVMU00xUVJrRDRweS9WVmpVUU1jUzBrSVFGUVV2UGRibTNOaG5FQjNETTdFWDJSdmh0UUdVY25hNXovcU0KeXFnUlJzZC9iOTlOYjNQSmxWdmg1alpYa3F6RGZBcUJYY3YzQzFmMk1iczRjUUtITXhaYk91WlgwOE94c3Jsbwp4clBKcE12L1dZTWpBbHJxWDZuWEUxL0FjVEptUnRDakVLMm9Zakh3RGorSWxyTWp5aWY2VjRKMitzMTJpQzJJCnRNc2VON09JZkErL0lXSUMwZUFXZFdzdnhScXdHdjhPbEJDck5sYXQzMkdpZmZCV3BtcXdMWkdEN1E1WFBKaGQKS3oyWlFlRUNnWUVBMkpHL09EWUZwa0dvaUpJRG9MOTM3Kzl6ZWJXd3Vmalc0djZ2L202Qm9EclRuQ1BwWVJ3ZQo4bDJ6U1E5RzA1TXRrNDZNNmlWZHREaVg4UkVzNWZxVjc3V3JHN1BiUk0yaDlkZmRZdEdDaFhudDdCYmtrWjlLCkJJRU4yZTJ5ajJYNGkwemYvSUFCVnpET2xra25FQjM2UEp6cTE5WWYvMDJsUUprOGlzRGY1VU1DZ1lFQTM5YU8Kc3hvVkJFQTc2MXFxZDlzQllNbW1GcXlMRmNTODV5YWhwM0ZodzlxU0xIcCs1a0tmN2dYTnFZYzhJUkE1QkZvRgpCMUxkS1pHNWlYYS9mSDlHQWRocUs4K3AwMmJtOWRxSUM0N1BHaHUra2ZpNWJXUnh2WnlxcnJOZmsvazNOTGlqCnJUU0RqNWZQSWNZcEhHYVcwYmNudnExdy93TWV0bzJ4QXQ5aWI4Y0NnWUVBaHZsSEVQUnlUdTBLNlpyL0VkZGoKRzdIRDZXMzRaOStUcGNPUDBtWHkrZmJQM2Jkd0EycndTcU5sVXJwbnJRTkVXM3R6alphZU1PMDRuVERVSjcwbQpaMUIxQlAzeVFZNWJTNG91MnlDeVZSZnAxY05xenV0VXlUdlpjeUkyc0RLZ1Zja2lyQTduUnYwUE5CRUJmSVVDCmFYWnUwdmdMMXlVQVFpTiszUWRhUTFzQ2dZRUF6RGtrQlVEY3YvNGpMVDZSbmIwUmFzOVFYQXVjOG9XSG5KWmcKa3pjZGJlWXp5NlVQdHVJK3JKcGE1RHZnbm9JQW8zbkdjTUlueXMrTUttRlBvRFUzR0dQdHFuOVRnTyszOWNRbQpyL1RoKy80b1IySlpPL2VTMXQ3ajAzVVExUjlpUVJYZE1DQmprRlYveEY3YUQzR0NWV0Q0UUQ1YWhERENpdWlJCkFnang5TzBDZ1lCT09vYklvaXpSdEEzeFFmU3hQbWJuZ05nSDdXcEhjb1p2WUVJZ2dFeStrOVhqTElmckpBbmoKeWFIa25BK2VsMUEzam1LTGlOL0JmR04vbXlaT3A2SU1EMGR6Y3dIQ1AxRzhFQW5CZVRNd3FTMGVxTG51SEFzYQpzNVRCZCtTU0VGUUVZQ29VYjNhR04wNnhiTTBva0UrZFphR3BLRkdMbHJnZDNJZFBzZDB1TXc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-ssl-internal
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQWR5Z0F3SUJBZ0lVSEt2L2xhWUdUVkF4QkIyY0poTnBjcldVZ3ZBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF4TUhVbTl2ZENCRFFUQWVGdzB4T1RBMU1EY3hNakF3TURCYUZ3MHlOREExTURVeApNakF3TURCYU1CSXhFREFPQmdOVkJBTVRCMUp2YjNRZ1EwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRRENIdHc2Q0hwRzloSUFNN2NLVWpmWElYSzhOWDlwRUpIQWpLL0tWbmQzY2xUWHFwRzYKQmdPRXlINytsSExaVGEwZnZncjJPUVFCc0pzaE9RSzRVb294ajg1SWNkTHkvbzE1c0xTVEl6VGJmZjZRMXljSQpGais3Si9RVTF1Njg2cGQzS3hGWFhURUxjNDE3Q2Jxdk9PWlIwRjExaUh2MUZvUld4eWdwK2x0WmxKcnNleFUvCkxvUEQveHM3WXQ1ZzEyZm92KzFud1hWOU9ad2wySmpvZFpjcjkwNmxvR2dkVEFKMmZlaUhSL2c5aXY5c2dhcHYKaHhiTUpRWEhHZFdMdzRPMTRtV1BDeHd0S3JZbWR1bVNEb2QwNmQxZFp0MmRocVRyVkp6SHdjUE0veWt6SWZPTAo5bElteVJ4ekdVMGU4M3BkOXdIYm5sdXphaGJxTldUY3Y0TnJBZ01CQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFCkF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlEwN0dlVFhTSnNSUExaT0R4NTlGY3cKUXAvdHlUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNT0h6R1hzbEptNXpocExzSmFvZ2NuQS9ieWpYcHB0MApxaGRGQmUwZEkvelJ6NDFOaFg1R3dYSEdPOHNMU2hjN0s2Tm1UQjhLUGwwanJFWkdvaHJhQWhCMWIycDF4YUpnCmRKa21XMnNYNUhRVDdIaXYrdk1UQWlNQ1YvS0Y1ZFJrOWkzWE9XN1k5eWNLYXYxTGhBSFRzZmExUUpDYS8wLzMKeGhsMGlxYWZBTmV3eUR0S2NQdlgzNVI5TGM5Q01vZUVFUW1QQ0xXMW9pZi80OHVjOEhZQUVsdGNMVWdnV2E1TwpSVnZBTTVhdXVWdG03Y2lDanNHckZEUzhYQnZ6NCt0eFJHY01lcW9SMDdWcUhqQ0gyb2YxRU5rdEkyRmMxUTEyCmYrV1JTdEtGUENNcmY3MG5jUEtiZitadVVCNmwvVStmWW9DaGVleENWYnkzWVNpdXRTSG41dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnekNDQW11Z0F3SUJBZ0lVY0I4c2JRUkRxb2VDemhhMUhnQTFqQVpHTlRjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF4TUhVbTl2ZENCRFFUQWVGdzB4T1RBMU1EY3hNakF3TURCYUZ3MHlNREExTURZeApNakF3TURCYU1CY3hGVEFUQmdOVkJBTVRER05zZFhOMFpYSXhMWEI0WXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1GTTExWWRZamtoaHE2Y3VjdXJJam5ZUFR3NEtxbXYwbm5WVXRMVkxlbUgKUWl5K09QbExmVDM4cFVpTzBQa1g5YTZUL01EV2VEWnhwbGRSdURVbzFHYjgrcFZvR3lXbldBdkFHWktzVUk2ZApUWWxpQ3lDOWEzeXB0aFEra1A4cHJPWmFWNkc2eDRuOTBHTEZ1OG0wNmJXUC9kUTdvbWRvb2ttbWx6UFEzckJvCjFEWDd5QkZrYlV6dTJsVk5OYk5UR1BrYWc0NWRLcHNWeG8yYnlaY0Zvd2kxWDdkWVEvK1Q5WnNxblFFN0hJb08KNmxzREJlRkptajhSdzg3Snp3dWtleUlaK3FkK2pLRXZvckJKSXA1WHpiSlB3aENKaENST3plajU3Y05oeWRLNgoyR25IdmVtWW9ZWU1FTURjclY3cTV2TDgxZko5cG1Ea2YyT2taemxZNnNVQ0F3RUFBYU9CeXpDQnlEQU9CZ05WCkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWQKRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkZoTkxQVDRZYzFBOXJNTThpeXFLanFOcW5lNU1COEdBMVVkSXdRWQpNQmFBRkRUc1o1TmRJbXhFOHRrNFBIbjBWekJDbiszSk1Fa0dBMVVkRVFSQ01FQ0NFV05zZFhOMFpYSXhMWEJ5CmIzaDVjM0ZzZ2hzcUxtTnNkWE4wWlhJeExYQnliM2g1YzNGc0xYVnVjbVZoWkhtQ0Rpb3VZMngxYzNSbGNqRXQKY0hoak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzdBTUlDbXVkNVRBcWpYeENLKzJaMkpjRVhXWE5iM1ZYdgovWlVQbDZBRFJlNi9zMGdQVGNFVno5RkJ0N2VGZXl5emlQT2t0WmFqOTBCSXhDZko3OW5oeUI4U29scVNBc0p1CkNwTXJlWjFNd21zR3FZNi83S1VQK3VrSStzUkkxYVNuVnQ2VXczM0NNQ3JUM2lIUWZPUWdraVE5Zkc3dGU5NFAKb3dTRGRpN1RNdmwzMW1pMUVGY2pFN2YrVGJlT2ZQTzh2OTF0cUhPTnBPK2hwTkxseDNFMEhQVDNFM0ppTDBrRwp2K1JldGJtVFhWa1lSMlZ1cmpaa2VpcWNBQnY4UjR4VndEejVRb05qcTJ1eHBvZmRaRS9TSE14U2Qxc2Z0a2prCkFOMldSbTZyck1tSXBRRDdxcFJXbmROVWlsZUJabVZWL2VOZTNNWHl5OWdjV0NOaXAyck8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBd1V6WFZoMWlPU0dHcnB5NXk2c2lPZGc5UERncXFhL1NlZFZTMHRVdDZZZENMTDQ0CitVdDlQZnlsU0k3UStSZjFycFA4d05aNE5uR21WMUc0TlNqVVp2ejZsV2diSmFkWUM4QVprcXhRanAxTmlXSUwKSUwxcmZLbTJGRDZRL3ltczVscFhvYnJIaWYzUVlzVzd5YlRwdFkvOTFEdWlaMmlpU2FhWE05RGVzR2pVTmZ2SQpFV1J0VE83YVZVMDFzMU1ZK1JxRGpsMHFteFhHalp2Smx3V2pDTFZmdDFoRC81UDFteXFkQVRzY2lnN3FXd01GCjRVbWFQeEhEenNuUEM2UjdJaG42cDM2TW9TK2lzRWtpbmxmTnNrL0NFSW1FSkU3TjZQbnR3MkhKMHJyWWFjZTkKNlppaGhnd1F3Tnl0WHVybTh2elY4bjJtWU9SL1k2Um5PVmpxeFFJREFRQUJBb0lCQUJlVXd6UkxNMTlhMnE1VQppa254WDZTRTM3dUg4cFJ1MFpOeFZjQklwMmcweXZyZ1hkenp1NXlqUkpxY2FadnBzMXdQeTZiT3d5MkpJY3pICk9GeXIxWFdXNlE3dSsxalZtR1VlazBBVWEyTnFoem42VHZjNGhITloxTStWYm1UaWRhaElYeVpvdmN6MHZNWS8KN3cvRlZUbUVEbWdrdWtRNVBJc1ZtcDZFblpZUmpUeEdKRWVwemllUTk4ZmF2QTF1Z1VtVS91RmYzY1RrRWxrVApYTnNobEZsbjRLWmdPN2N6MVRRLzFzUG5iNFVjL2ZCUWJZeVJkOGRDTEQzNXhFSWxtRlhWUzZCQVlyOHZLVFdMCmxOUU9sQ2xHZjFLa0dLemc2d3FjQU5lS2I3SUs2c2VGMXo1V1lPRGdUK3RFcldNZ3B1Q3RVck5DQkltVFdoYjQKQXljUEcyRUNnWUVBeVEva0VsMGg5QXNhZWJtYzNVSzBMYktRR21LMVN2RWtNanZwNWhINGhjU1hrMjNab1JjWQoveXJ6dlJ0NVNvY3B4Z3M4NGY0eGJCK0N5TkpIZjlrZ2x5cStVK1pFYWptTU82QWREYmRFQUpadFZrVUZGZWE1Clh1dDFjQTcwM01CdU5BODdCRno2MEJBaUROdjU1WHdpK05wTVZHSlJOTEZtWlNpaFMrSG9CdGtDZ1lFQTloNEMKOFcxK0lmMmZnRkJNR0FLbGJaZ2VYRWxnNFhiNUVIenVZSEl0Y0d3cWlra2xiUGp6L0RzNFNITjRwQnZyR0l6cgpvOWJVaXZWQyt4d1VtZTlQVklqdXpQZ2I2RldVK3lJVC9acUpWdld5RFR4SFF5UjJCa1Nadk9VV1JiZzFITzFQClFQejhuMStHcWVZMkxBVEk5RnloS0F4enlvM1gxVkFza1o4SGg4MENnWUFOUDB6Sm9QVkJ2UkdMZjUxRVBzYmMKVSsyR3I0WStYOUVBdGszYzZNWTFHaFRhazl4STd0cW94VTIxNGYrRjE0MzdESGFBZFYwUVFLcy9UQXVGOHVwZwp5MklxNlBzTS9LbXVyQWYrQlZzbnBzR2hjMzY0U0xGaC9hV0pNcE1Ua0dJeWIrWjFqU0xCWHE2L3BpYTY1Z2p2CjJJSTY5UmRnbjJlZHRxV1orRkp2VVFLQmdRREFlYVlKazN5aUxvdnZ1RnhhSnErakx1VUhmV2RqekR4cU5abmoKR1VnSjlMMnNHaHBIeDhaZnl4eHdKTVlEYWNZSkZDUXdwSkRoLzM4YmpORmJ0WGpQL3FycTUxcEQ3N0lzV0hGVAowdWgzZG55QnQxTnY0ZkxmWWdUdFlpZHg3T2Ewc2E1YWY3ODlFR0xyT2h2QmZ4aDlhbmVxTDFyYTNPVWZjS3o2ClVXbDlQUUtCZ1FDQmpSZ2RpUjRZd1R1SXFnMHVIaVRRZzRFTEdVZnY1akFER0ovWnZZdlplWkdJN3V5MUVMMmgKTm9FaUpZLy9YdjY2OEQ0NXVlTkU5NVRPeXZqS0Fjck1EUkQwQi9FcXJsbk0xTU5kMStXdlBkWkFFU2ZJc3BEbgpkczZEOXExZzBzWW5YRUdyWmtEbW02dDJOMEM5Y05lZ1oyYXlRVFVOdHNsTUxTOVZmSlZQWEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

