apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secrets
type: Opaque
data:
  root: cm9vdF9wYXNzd29yZA==
  xtrabackup: YmFja3VwX3Bhc3N3b3Jk
  monitor: bW9uaXRvcg==
  clustercheck: Y2x1c3RlcmNoZWNrcGFzc3dvcmQ=
  proxyadmin: YWRtaW5fcGFzc3dvcmQ=
  pmmserver: c3VwYXxefHBheno=
