apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: perconaxtradbclusterbackups.pxc.percona.com
  labels:
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/version: v1.19.0
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: percona-xtradb-cluster-operator
